version: 2.1
jobs:
  run_test:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: pip install --user -r requirements.txt
      - run:
          name: "Run tests"
          command: |
            flake8 --exclude=venv* --statistics --output-file test-reports
            pytest -v --cov=calculator
      - store_artifacts:
          path: test-reports
          destination: test-reports
            
workflows:
  version: 2.1
  build-tests:
    jobs:
      - run_test
