version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: "Install Python Dependencies 1"
          command: echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
      - run:
          name: "Install dependencies"
          command: pip install --user -r requirements.txt
      - run:
          name: "Run tests"
          command: |
            pytest -v --cov=calculator
            flake8 ./ test --output-file test-reports
      - store_artifacts:
          path: test-reports
          destination: test-reports
            

