version: 2.1
jobs:
  calculator-test:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: "Install dependencies"
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: "Run Linter"
          working_directory: ~/repo
          command: |
            mkdir -p test-reports/flake8
            flake8 . --output-file=test-reports/flake8/flake8.txt
      - run:
          name: "Check for warnings."
          command: |
            if [ -f .flake8warnings ]; then
              flake8 --append-config=.flake8warnings
            else
              flake8 --extend-ignore="$FLAKE8_ERRORS"
            fi
          when: always
      - run:
          name: Check for errors.
          command: |
            if [ -f .flake8errors ]; then
              flake8 --append-config=.flake8errors
            else
              flake8 --extend-ignore="$FLAKE8_WARNINGS"
            fi
          when: always

      - run:
          name: "Run tests"
          command: |
            . venv/bin/activate
            pytest -v --cov=calculator
            flake8 --exclude=venv* --statistics
            flake8 . --bug-report
            flake8 . --benchmark
            flake8 . --count
          when: always
      - run:
          name: "Run test2"
          working_directory: ~/repo
          command: coverage run test_calculator.py test
          when: always
      - run:
          name: "Create Test Reports"
          working_directory: ~/repo
          command: |
            . venv/bin/activate
            flake8_junit test-reports/flake8/flake8.txt test-reports/flake8/flake8_junit.xml
            coverage html -d test-reports/coverage
          when: always
      - store_test_results:
          path: test-reports
      
      - store_artifacts:
          path: test-reports
          destination: tr1

workflows:
  version: 2.1
  calculator-test-result:
    jobs:
      - calculator-test:
          filters:
            branches:
              only: master
