version: 2.1
jobs:
  run_test:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --user -r requirements.txt
      - run:
          name: "Run tests"
          command: |
            flake8 --exclude=venv* --statistics
            pytest -v --cov=calculator
            
workflows:
  version: 2.1
  build-tests:
    jobs:
      - run_test
