version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: "Install dependencies"
          command: pip install --user -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: "Run Linter"
          working_directory: ~/workspace/src
          command: |
            mkdir -p test-reports/flake8
            flake8 . --output-file=test-reports/flake8/flake8.txt
      - run:
          name: "Run test"
          working_directory: ~/workspace/src
          command: coverage run calculator test
      - run:
          name: "Create Test Reports"
          working_directory: ~/workspace/src
          command: |
            mkdir -p myapp/test-reports/flake8
            flake8_junit test-reports/flake8/flake8.txt test-reports/flake8/flake8_junit.xml
            coverage html -d test-reports/coverage
          when: always
      - store_test_results:
          path: myapp/test-reports
      
      - store_artifacts:
          path: myapp/test-reports
          destination: tr1
