version: 2.1
jobs:
  run_test:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: "Install Python Dependencies 1"
          command: echo 'export PATH=~$PATH:~/.local/bin' >> $BASH_ENV && source $BASH_ENV
      - run:
          name: "Install dependencies"
          command: pip install --user -r requirements.txt
      - run:
          name: "Run tests"
          command: |
            mkdir test-results
            flake8 ./ tests --output-file test-reports.txt
            pytest -v --cov=calculator
      - store_artifacts:
          path: test-reports
          destination: test-reports
            
workflows:
  version: 2.1
  build-tests:
    jobs:
      - run_test
